name: Documentation generation

on:
  push:
    branches:
      - master
      - test-ci
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Generate documentation
        working-directory: ./packages/API
        run: yarn docgen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/API/docs
          commit_message: Deploy docs for ${{ github.event.head_commit.message }}
