name: Unit tests

on: [push, pull_request, workflow_dispatch]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        working-directory: ./API
        run: yarn
      
      - name: Check types
        working-directory: ./API
        run: yarn test --ci

